baseURL = "https://arporfolio.netlify.com"
languageCode = "The language code for the language the website is written in"
title = "AR PROJECTS"
theme = "aether"
googleAnalytics = "Your google analytics tracking ID - optional"
disqusShortname = "Your shortname for Disqus - optional"

[params]
brand = "xristlxcv"
description = "The website's description"
homeimg = "URL to the image used for the home button at the bottom of each post - optional"
bgimg = "URL to the image used for the page background - optional"
rssinmenu = false